name: Close inactive issues
on:
  workflow_dispatch:
  schedule:
    - cron: "25 13 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 720
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: ":warning: This issue is stale because it has been open for 720 days with no activity. Please chime in if you want to keep it alive."
          close-issue-message: ":no_entry: This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
